name: CI ‑ HuskSync

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tagss'
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build & Test
        run: ./gradlew clean build test

      - name: Upload artifacts (jar outputs and test reports)
        uses: actions/upload-artifact@v4
        with:
          name: husksync-artifacts
          path: |
            build/libs/*.jar
            build/reports/tests/**/*.xml

  release:
    runs-on: ubuntu-latest
    needs: build
    if: |
      github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      || github.event_name == 'workflow_dispatch'
    steps:
      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2.3.1
        with:
          tag_name: ${{ github.event_name == 'push' && github.ref_name || github.inputs.tag }}
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload test report to issue/docs
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/**

